numeros = [1, 2, 3]
letras = ["a", "b", "c"]
palabras = ["chanchito", "feliz"]
palabrasFelices = ["chanchito", "feliz", "Felipe", "alumno"]
booleans = [True, False, True, True]
matriz = [[0, 1], [1, 0]]  # <-lista con listas
ceros = [0] * 10
alfanumerico = numeros + letras  # <-Super listas
rango = list(range(1, 11))
chars = list("Hola mundo")
